name: Check Keys 
on:
  workflow_dispatch:
jobs:
  check:
    runs-on: ubuntu-latest
    environment: pr
      AK: ${{ secrets.ACCESS_KEY_ID }}
      COMPARE: ${{ secrets.TEST }}
    steps:
      - name: Compare
        run: |
          if [[ $AK == $COMPARE ]]; then
              echo "Rotate These Keys"
              exit 0
          else
              exit 1
          fi
